services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GROQ_KEYS: ${GROQ_KEYS}
      LLAMA_API_KEY: ${LLAMA_API_KEY}
    volumes:
      - shared-voices:/voices
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
  celery:
      build:
        context: .
        dockerfile: bot/Dockerfile 
      command: ["celery", "-A", "bot.tasks", "worker", "--loglevel=INFO", "-P", "solo"]
      environment:
        BOT_TOKEN: ${BOT_TOKEN}
        GROQ_KEYS: ${GROQ_KEYS}
        LLAMA_API_KEY: ${LLAMA_API_KEY}
      volumes:
        - shared-voices:/voices
      depends_on:
        - redis
        - bot
      restart: always


volumes:
  shared-voices: