"""create chat_settings table

Revision ID: b23a9c06b418
Revises: 
Create Date: 2026-08-06 01:45:32.550014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23a9c06b418'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_auto_mode', sa.Boolean(), nullable=False),
    sa.Column('prompt_preset', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
